#!/usr/bin/env zsh

xrandr --output DP-0 --mode 3840x2160 --primary --pos 0x0 --rotate normal --output DP-2 --mode 1920x1200 --pos 3840x120 --rotate left
pgrep sxhkd || sxhkd &

for monitor in $(bspc query -M); do
  bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10
done
MONITOR=DP-0 polybar -r main &
MONITOR=DP-2 polybar -r main &

bspc config border_width 2
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

if (( $+commands[nitrogen] )) {
  nitrogen --restore &
}

if (( $+commands[wmname] )) {
  # Java swing support
  wmname LG3D
}
